### ISSUE TITLE
How to visualize result?

### ISSUE THREAD

**Issue by Traveleriocc** [ZhangCYG/U-RED#4]
The code provide has bug.

**Comment by ZhangCYG** [comment]
Can you provide more details?

**Comment by Traveleriocc** [comment]
First i change the feature dimension according to my config , https://github.com/ZhangCYG/U-RED/blob/5468a57aeaf2d7965282c9f57cdae78c5545c397/engine/vis.py#L97
then when i run vis.py, it gives this bug
![image](https://github.com/ZhangCYG/U-RED/assets/43273733/3510e36b-8d5e-466c-9b43-5bef38475407)

**Comment by ZhangCYG** [comment]
Can you reproduce the original config and experiment and find if there still isn't working?

**Comment by Traveleriocc** [comment]
Actually it's the config there provides, it doesn't work, the dimension is not correct in your config so i change it.

**Comment by Traveleriocc** [comment]
I just traing and testing by your pipeline, but visualization is not work.

**Comment by ZhangCYG** [comment]
Ok, I might know what happens. I will fix it and upload in a few days.

**Comment by ZhangCYG** [comment]
I have push the fixed version and update the README file about the visualization.
