### ISSUE TITLE
How to prepare custom data?

### ISSUE THREAD

**Issue by Traveleriocc** [ZhangCYG/U-RED#5]
There are several data files to prepare, what if i want to organize a new catagory, how to prepare data? Especially for .h5 file in data/data_aabb_constraints_keypoint, can you explain what this data is and how to prepare is?
![image](https://github.com/ZhangCYG/U-RED/assets/43273733/b1d0d5cd-2899-4416-9179-f20d35376cbd)

**Comment by ZhangCYG** [comment]
If still using the prepared PartNet database works for you, only to adapt new data for the input partial target point clouds is rather easy -- just modifying the dataset. If you must change the PartNet database, I would suggest you to refer to https://github.com/mikacuy/joint_learning_retrieval_deformation for the detailed instructions for database construction. I hope it may help you.
